# Generated by Django 4.2.9 on 2025-05-12 22:47

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contact_tag_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='skills_tags',
            field=models.ManyToManyField(to='portfolio.tag'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=djrichtextfield.models.RichTextField(max_length=800),
        ),
    ]
