# Generated by Django 4.2.9 on 2025-05-18 18:33

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about_skills_tags_alter_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='icon',
            field=models.CharField(default='code', max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='certifications',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=djrichtextfield.models.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='about',
            name='experience',
            field=djrichtextfield.models.RichTextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='about',
            name='skills',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='greeting',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
