# Generated by Django 4.2.9 on 2025-05-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_homepage_icon_alter_about_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='icon',
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_intro2',
            field=models.CharField(default='I am drawn to predictive analytics for problem-solving side of tech, where data meets decision-making.', max_length=2000),
        ),
    ]
