# Generated by Django 4.2.9 on 2025-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_homepage_icon_homepage_description_intro2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description_intro2',
            field=models.CharField(max_length=2000),
        ),
    ]
