# Generated by Django 5.2.3 on 2025-06-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_homepage_description_intro2'),
    ]

    operations = [
    ]
