# Generated by Django 5.2.3 on 2025-06-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_merge_migrations'),
        ('portfolio', '0008_merge_migrations'),
    ]

    operations = [
    ]
